# Generated by Django 4.1 on 2022-08-30 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_profile_password_remove_profile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_verify',
            field=models.BooleanField(default=False),
        ),
    ]
