# Generated by Django 4.0.6 on 2022-09-07 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_profile_address_profile_city_profile_code_meli_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='province',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='receiver_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
