# Generated by Django 4.0.6 on 2022-08-28 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_product_created_product_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zir_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('sargroh', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.category', verbose_name='سردسته')),
            ],
        ),
    ]
