# Generated by Django 4.0.6 on 2022-08-28 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_zir_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='alt',
            field=models.CharField(max_length=100, null=True, verbose_name='توضیح عکس'),
        ),
        migrations.AddField(
            model_name='company',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='عکس کمپانی'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='اسم کمپانی'),
        ),
    ]
