# Generated by Django 4.0.6 on 2022-08-28 04:08

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_company_alt_company_image_alter_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='توضیح دسته بندی'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200, verbose_name='نام دسته بندی'),
        ),
    ]
