# Generated by Django 4.0.6 on 2022-08-30 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_remove_product_color_remove_product_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='color',
            name='Ekhtelaf',
            field=models.IntegerField(null=True, verbose_name='اختلاف قیمت'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_asli',
            field=models.IntegerField(null=True, verbose_name='قیمت اصلی'),
        ),
        migrations.AddField(
            model_name='size',
            name='Ekhtelaf',
            field=models.IntegerField(null=True, verbose_name='اختلاف قیمت'),
        ),
    ]
