# Generated by Django 4.0.6 on 2022-08-30 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_remove_product_price_color_ekhtelaf_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name': 'رنگ های بیشتر', 'verbose_name_plural': 'رنگ های بیشتر'},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'verbose_name': 'سایز های بیشتر', 'verbose_name_plural': 'سایز های بیشتر'},
        ),
        migrations.RemoveField(
            model_name='color',
            name='name',
        ),
    ]
