# Generated by Django 4.0.6 on 2022-09-11 15:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_product_tedad_mahsole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tedad_mahsole',
            field=models.PositiveBigIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='تعداد محصول'),
        ),
    ]
