# Generated by Django 4.0.6 on 2022-08-27 08:09

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='اسم سایت')),
                ('logo', models.FileField(null=True, upload_to='', verbose_name='لوگو')),
                ('alt', models.CharField(max_length=100, null=True, verbose_name='توضیحات لوگو')),
                ('favicon', models.FileField(null=True, upload_to='', verbose_name='آیکون')),
                ('alt2', models.CharField(max_length=100, null=True, verbose_name='توضیحات icon')),
                ('text', models.CharField(max_length=500, null=True, verbose_name='متن')),
                ('telephon', models.CharField(max_length=30, null=True, verbose_name='تلفن')),
                ('email', models.EmailField(max_length=100, null=True, verbose_name='ایمیل')),
                ('address', models.CharField(max_length=200, null=True, verbose_name='ادرس')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=False, verbose_name='نمایش داده شود؟')),
            ],
        ),
        migrations.CreateModel(
            name='Tabligh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='TagNav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='تگ ها')),
            ],
        ),
        migrations.CreateModel(
            name='TagNewPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='تگ ها')),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_bold', models.CharField(max_length=300, verbose_name='متن بولد')),
                ('text_simple', models.CharField(max_length=300, verbose_name='متن ساده')),
                ('text_dir', models.CharField(choices=[('right', 'right'), ('center', 'center'), ('left', 'left')], max_length=20, verbose_name='پوزیشن متن')),
                ('image', models.ImageField(upload_to='', verbose_name='عکس سلایدر')),
                ('alt', models.CharField(max_length=100, verbose_name='توضیح عکس')),
                ('name_button', models.CharField(max_length=100, verbose_name='متن دکمه')),
                ('link', models.CharField(blank=True, max_length=100, null=True, verbose_name='ادرس صفحه')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='بدنه')),
                ('url_title', models.CharField(blank=True, max_length=300, null=True, verbose_name='نام صفحه')),
                ('text', models.TextField(blank=True, null=True, verbose_name='متن')),
                ('tag', models.ManyToManyField(blank=True, to='home.tagnewpage', verbose_name='تگ ها')),
            ],
        ),
        migrations.CreateModel(
            name='NavAsli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('link', models.CharField(blank=True, max_length=100, null=True, verbose_name='ادرس صفحه')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='بدنه')),
                ('url_title', models.CharField(blank=True, max_length=300, null=True, verbose_name='نام صفحه')),
                ('text', models.TextField(blank=True, null=True, verbose_name='متن')),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.navasli')),
                ('tag', models.ManyToManyField(blank=True, to='home.tagnav', verbose_name='تگ ها')),
            ],
            options={
                'verbose_name': 'نوبار',
                'verbose_name_plural': 'نوبارها',
                'ordering': ['name'],
            },
        ),
    ]
