# Generated by Django 4.0.6 on 2022-08-27 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_slider_text_simple'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='text_simple',
            field=models.CharField(max_length=300, null=True, verbose_name='متن ساده'),
        ),
    ]
