# Generated by Django 4.0.6 on 2022-08-27 09:04

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_slider_text_simple'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterAsli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FooterZir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('link', models.CharField(blank=True, max_length=100, null=True, verbose_name='ادرس صفحه')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='بدنه')),
                ('url_title', models.CharField(blank=True, max_length=300, null=True, verbose_name='نام صفحه')),
                ('text', models.TextField(blank=True, null=True, verbose_name='متن')),
                ('footer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.footerasli')),
                ('tag', models.ManyToManyField(blank=True, to='home.tagnav', verbose_name='تگ ها')),
            ],
        ),
    ]
