# Generated by Django 4.0.6 on 2022-08-27 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_footerasli_footerzir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footerzir',
            name='link',
            field=models.CharField(max_length=100, null=True, verbose_name='لینک صفحه'),
        ),
    ]
