# Generated by Django 4.0.6 on 2022-08-27 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_tabligh_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='text_vasat_nav',
            field=models.CharField(max_length=100, null=True, verbose_name='متن وسط نوبار'),
        ),
    ]
