# Generated by Django 4.0.6 on 2022-08-27 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_sitesetting_text_vasat_nav'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم کمپانی')),
                ('image', models.ImageField(upload_to='', verbose_name='عکس کمپانی')),
                ('alt', models.CharField(max_length=100, verbose_name='توضیح عکس')),
            ],
        ),
    ]
