# Generated by Django 4.0.6 on 2022-08-28 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_sitesetting_alt_bg_sitesetting_image_bg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
    ]
