# Generated by Django 4.1 on 2022-09-04 20:29

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=18, null=True, samples=None),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='size',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
